# Generated by Django 6.0.3 on 2026-03-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='cargo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('DIRETOR', 'Diretor'), ('COORDENADOR', 'Coordenador'), ('AUX_COORD', 'Auxiliar de Coordenação'), ('ORIENTADOR', 'Orientador Educacional'), ('SECRETARIA', 'Secretaria'), ('PROFESSOR', 'Professor'), ('INSPETOR', 'Inspetor')], default='PROFESSOR', max_length=20),
        ),
    ]
