# Generated by Django 6.0.3 on 2026-03-12 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gradehoraria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradehoraria',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_horaria', to='core.professor'),
        ),
    ]
