# Generated by Django 6.0.3 on 2026-03-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_gradehoraria_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email_responsavel',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Responsável'),
        ),
        migrations.AddField(
            model_name='professor',
            name='cpf',
            field=models.CharField(blank=True, help_text='Formato: 000.000.000-00', max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='professor',
            name='turmas_inspetor',
            field=models.ManyToManyField(blank=True, help_text='Turmas pelas quais este inspetor é responsável', related_name='inspetores_responsaveis', to='core.turma', verbose_name='Turmas (Inspetor)'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='turmas',
            field=models.ManyToManyField(blank=True, related_name='professores', to='core.turma'),
        ),
    ]
