# Generated by Django 6.0.3 on 2026-03-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_cpf_inspetor_turmas_email_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspetorProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Inspetor',
                'verbose_name_plural': 'Inspetores',
                'ordering': ['nome'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.professor',),
        ),
        migrations.CreateModel(
            name='ProfessorDocente',
            fields=[
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ['nome'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.professor',),
        ),
    ]
