# Generated by Django 6.0.3 on 2026-03-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_proxy_models_inspetor_professor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['ordem_exibicao', 'codigo']},
        ),
        migrations.AddField(
            model_name='turma',
            name='ordem_exibicao',
            field=models.IntegerField(default=0),
        ),
    ]
