# Generated by Django 6.0.3 on 2026-03-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_turma_ordering_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['turma__ordem_exibicao', 'turma__codigo', 'nome']},
        ),
    ]
