# Generated by Django 4.2.29 on 2026-03-16 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_update_aluno_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugestaoConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('ordem', models.IntegerField(default=0)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes', to='core.disciplina')),
                ('turmas', models.ManyToManyField(blank=True, related_name='sugestoes_conteudo', to='core.turma')),
            ],
            options={
                'verbose_name': 'Sugestão de Conteúdo',
                'verbose_name_plural': 'Sugestões de Conteúdo',
                'ordering': ['disciplina', 'ordem', 'texto'],
            },
        ),
    ]
