# Generated by Django 6.0.3 on 2026-03-25 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sugestaoconteudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_periodo_letivo', models.DateField(default=datetime.date(2026, 2, 3), verbose_name='Início do Período Letivo')),
                ('fim_periodo_letivo', models.DateField(default=datetime.date(2026, 12, 18), verbose_name='Fim do Período Letivo')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
