# Generated by Django on 2026-03-19

from django.db import migrations

def merge_disciplines_and_sort_turmas(apps, schema_editor):
    Disciplina = apps.get_model('core', 'Disciplina')
    Turma = apps.get_model('core', 'Turma')
    GradeHoraria = apps.get_model('core', 'GradeHoraria')
    Ocorrencia = apps.get_model('core', 'Ocorrencia')
    ConteudoProgramatico = apps.get_model('core', 'ConteudoProgramatico')
    SugestaoConteudo = apps.get_model('core', 'SugestaoConteudo')

    # Merge Physics Disciplines
    merges = [
        (39, 4),   # Fisica -> Física
        (40, 35),  # Fisica II -> Física II
    ]

    for old_id, new_id in merges:
        try:
            d_old = Disciplina.objects.get(id=old_id)
            d_new = Disciplina.objects.get(id=new_id)
            
            GradeHoraria.objects.filter(disciplina=d_old).update(disciplina=d_new)
            Ocorrencia.objects.filter(disciplina=d_old).update(disciplina=d_new)
            ConteudoProgramatico.objects.filter(disciplina=d_old).update(disciplina=d_new)
            
            for s in SugestaoConteudo.objects.filter(disciplina=d_old):
                s.disciplina = d_new
                s.save()
            
            d_old.delete()
        except Disciplina.DoesNotExist:
            pass

    # Update Turma Ordering
    TURMA_ORDER = ['61', '62', '63', '71', '72', '73', '81', '82', '83', '91', '92', '93', '11', '12', '13', '21', '22', '23', '31', '32']
    for index, codigo in enumerate(TURMA_ORDER, start=1):
        Turma.objects.filter(codigo=codigo).update(ordem_exibicao=index)

def rollback_disciplines_and_sort_turmas(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sugestaoconteudo'),
    ]

    operations = [
        migrations.RunPython(merge_disciplines_and_sort_turmas, reverse_code=rollback_disciplines_and_sort_turmas),
    ]
