# Generated by Django 6.0.3 on 2026-04-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_disciplines_sort_turmas'),
        ('core', '0011_configuracao_feriados'),
    ]

    operations = [
    ]
