# Generated by Django 6.0.3 on 2026-04-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_professor_deve_trocar_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='email_contato',
            field=models.EmailField(blank=True, help_text='E-mail pessoal do professor para comunicações e recuperação de senha.', max_length=254, null=True, verbose_name='E-mail de contato'),
        ),
    ]
