# Generated by Django 6.0.3 on 2026-04-08 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_email_contato_professor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudoprogramatico',
            name='confirmado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em'),
        ),
        migrations.AddField(
            model_name='conteudoprogramatico',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteudos_confirmados', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
        migrations.AddField(
            model_name='conteudoprogramatico',
            name='confirmado_secretaria',
            field=models.BooleanField(default=False, help_text='Quando confirmado, o professor não pode mais editar ou excluir o lançamento.', verbose_name='Confirmado pela Secretaria'),
        ),
    ]
