# Generated by Django 6.0.3 on 2026-04-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_email_contato_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto do aluno (será redimensionada automaticamente para 200×200 px).', null=True, upload_to='alunos/fotos/', verbose_name='Foto'),
        ),
    ]
