# Generated by Django 6.0.3 on 2026-05-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_confirmacao_secretaria'),
        ('core', '0015_aluno_add_foto'),
    ]

    operations = [
    ]
