# Generated by Django 6.0.3 on 2026-05-12 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20260512_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(unique=True, verbose_name='Ano')),
                ('atual', models.BooleanField(default=False, verbose_name='Ano Atual')),
            ],
            options={
                'verbose_name': 'Ano Letivo',
                'verbose_name_plural': 'Anos Letivos',
                'ordering': ['-ano'],
            },
        ),
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['turma__ano_letivo__ano', 'turma__ordem_exibicao', 'turma__codigo', 'nome']},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['ano_letivo__ano', 'ordem_exibicao', 'codigo']},
        ),
        migrations.AlterField(
            model_name='turma',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='ano_letivo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to='core.anoletivo'),
        ),
        migrations.AddField(
            model_name='turma',
            name='ano_letivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='core.anoletivo'),
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('codigo', 'ano_letivo')},
        ),
    ]
