# Generated by Django 6.0.3 on 2026-05-12 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_anoletivo_alter_aluno_options_alter_turma_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Escola')),
                ('codigo_inep', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código INEP')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Município')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['escola', 'ano_letivo__ano', 'ordem_exibicao', 'codigo']},
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='ano_letivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='core.anoletivo'),
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='core.escola'),
        ),
        migrations.AddField(
            model_name='professor',
            name='escolas',
            field=models.ManyToManyField(blank=True, related_name='professores', to='core.escola'),
        ),
        migrations.AddField(
            model_name='turma',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='core.escola'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracao',
            unique_together={('escola', 'ano_letivo')},
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('codigo', 'ano_letivo', 'escola')},
        ),
    ]
