# Generated by Django 6.0.3 on 2026-05-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_escola_alter_turma_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='cor_primaria',
            field=models.CharField(default='#1e3a8a', help_text='Ex: #1e3a8a', max_length=7, verbose_name='Cor Primária (Hex)'),
        ),
        migrations.AddField(
            model_name='escola',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='escolas/logos/', verbose_name='Logo da Escola'),
        ),
    ]
