# Generated by Django 6.0.3 on 2026-06-08 15:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_escola_cor_primaria_escola_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='fim_periodo_letivo',
            field=models.DateField(default=core.models._default_fim_periodo, verbose_name='Fim do Período Letivo'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='inicio_periodo_letivo',
            field=models.DateField(default=core.models._default_inicio_periodo, verbose_name='Início do Período Letivo'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='status',
            field=models.CharField(choices=[('Aberta', 'Aberta'), ('Resolvida', 'Resolvida')], db_index=True, default='Aberta', max_length=20),
        ),
    ]
