# Generated by Django 6.0.3 on 2026-06-09 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_configuracao_fim_periodo_letivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AulaExtraProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, verbose_name='Data da Aula Extra')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turma')),
            ],
            options={
                'verbose_name': 'Aula Extra Programada',
                'verbose_name_plural': 'Aulas Extras Programadas',
                'unique_together': {('data', 'turma', 'disciplina', 'professor')},
            },
        ),
    ]
