# Generated by Django 6.0.3 on 2026-06-11 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_aulaextraprogramada'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_boletim', models.CharField(max_length=100, unique=True, verbose_name='Nome no Boletim')),
                ('faz_simulado_ef', models.BooleanField(default=False, help_text='Disciplinas deste grupo recebem bônus de simulado para turmas do 8° e 9° ano do EF.', verbose_name='Simulado EF 8°/9°')),
                ('ordem_boletim', models.IntegerField(default=0, verbose_name='Ordem no Boletim')),
            ],
            options={
                'verbose_name': 'Grupo de Disciplina',
                'verbose_name_plural': 'Grupos de Disciplinas',
                'ordering': ['ordem_boletim', 'nome_boletim'],
            },
        ),
        migrations.AddField(
            model_name='configuracao',
            name='periodo_notas_fim',
            field=models.DateField(blank=True, help_text='Data de encerramento do período para professores lançarem notas.', null=True, verbose_name='Fim do lançamento de notas'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='periodo_notas_ini',
            field=models.DateField(blank=True, help_text='Data de abertura do período para professores lançarem notas.', null=True, verbose_name='Início do lançamento de notas'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='faz_simulado_ef',
            field=models.BooleanField(default=False, help_text='Usado apenas quando a disciplina não tem grupo definido.', verbose_name='Simulado EF 8°/9° (standalone)'),
        ),
        migrations.AddField(
            model_name='professor',
            name='autorizado_lancar_notas',
            field=models.BooleanField(default=False, help_text='Permite que o professor lance notas dentro do período de lançamento configurado.', verbose_name='Autorizado a lançar notas'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cargo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('DIRETOR', 'Diretor'), ('COORDENADOR', 'Coordenador'), ('AUX_COORD', 'Auxiliar de Coordenação'), ('AUX_ADMIN', 'Auxiliar Administrativo'), ('ORIENTADOR', 'Orientador Educacional'), ('SECRETARIA', 'Secretaria'), ('PROFESSOR', 'Professor'), ('INSPETOR', 'Inspetor')], default='PROFESSOR', max_length=20),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to='core.grupodisciplina', verbose_name='Grupo no Boletim'),
        ),
        migrations.CreateModel(
            name='NotaBimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.IntegerField(choices=[(1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')], db_index=True)),
                ('nota_prova', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Nota da Prova')),
                ('nota_simulado', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Nota do Simulado (interno)')),
                ('nota_final', models.DecimalField(decimal_places=1, editable=False, max_digits=4, verbose_name='Nota Final (calculada)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.aluno')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anoletivo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
                ('lancado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_lancadas', to='core.professor')),
            ],
            options={
                'verbose_name': 'Nota Bimestral',
                'verbose_name_plural': 'Notas Bimestrais',
                'ordering': ['aluno__nome', 'bimestre'],
                'unique_together': {('aluno', 'disciplina', 'bimestre', 'ano_letivo')},
            },
        ),
    ]
