# Generated by Django 6.0.3 on 2026-06-15 14:17

from django.db import migrations


def split_occurrences(apps, schema_editor):
    Ocorrencia = apps.get_model('core', 'Ocorrencia')
    # Para cada ocorrência com mais de um aluno
    for oc in Ocorrencia.objects.all():
        alunos_list = list(oc.alunos.all())
        if len(alunos_list) > 1:
            primeiro_aluno = alunos_list[0]
            for aluno in alunos_list[1:]:
                nova_oc = Ocorrencia.objects.create(
                    data=oc.data,
                    turma=oc.turma,
                    professor=oc.professor,
                    disciplina=oc.disciplina,
                    descricao=oc.descricao,
                    status=oc.status,
                )
                nova_oc.alunos.add(aluno)
            oc.alunos.set([primeiro_aluno])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_aulaextraprogramada'),
    ]

    operations = [
        migrations.RunPython(split_occurrences, reverse_code=migrations.RunPython.noop),
    ]
