# Generated by Django 6.0.3 on 2026-06-11 11:08

from django.db import migrations


GRUPOS = [
    # (nome_boletim, faz_simulado_ef, ordem, [nomes das sub-disciplinas])
    ('Matemática',        True,  1, ['Mat. I', 'Mat. II', 'Mat. III', 'Matemática']),
    ('Língua Portuguesa', True,  2, ['Português I', 'Português II', 'Português',
                                      'Leitura', 'Comp. Texto', 'Redação', 'Literatura']),
    ('Física',            False, 3, ['Física I', 'Física II', 'Física']),
    ('Química',           False, 4, ['Química I', 'Química II', 'Química III', 'Química']),
    ('Biologia',          False, 5, ['Biologia I', 'Biologia II', 'Biologia']),
    ('História',          False, 6, ['História I', 'História II', 'História']),
    ('Geografia',         False, 7, ['Geografia I', 'Geografia II', 'Geografia']),
]


def criar_grupos(apps, schema_editor):
    GrupoDisciplina = apps.get_model('core', 'GrupoDisciplina')
    Disciplina = apps.get_model('core', 'Disciplina')

    for nome, simulado_ef, ordem, nomes_disc in GRUPOS:
        grupo, _ = GrupoDisciplina.objects.get_or_create(
            nome_boletim=nome,
            defaults={'faz_simulado_ef': simulado_ef, 'ordem_boletim': ordem},
        )
        grupo.faz_simulado_ef = simulado_ef
        grupo.ordem_boletim = ordem
        grupo.save()

        for nome_disc in nomes_disc:
            Disciplina.objects.filter(nome=nome_disc).update(grupo=grupo)


def remover_grupos(apps, schema_editor):
    GrupoDisciplina = apps.get_model('core', 'GrupoDisciplina')
    Disciplina = apps.get_model('core', 'Disciplina')
    Disciplina.objects.update(grupo=None)
    GrupoDisciplina.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_nota_bimestral_grupo_disciplina_aux_admin'),
    ]

    operations = [
        migrations.RunPython(criar_grupos, remover_grupos),
    ]
