# Generated by Django 6.0.3 on 2026-06-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_data_grupos_disciplinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='notas_b1_fim',
            field=models.DateField(blank=True, null=True, verbose_name='B1 — Fim do lançamento'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='notas_b1_ini',
            field=models.DateField(blank=True, null=True, verbose_name='B1 — Início do lançamento'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='notas_b2_fim',
            field=models.DateField(blank=True, null=True, verbose_name='B2 — Fim do lançamento'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='notas_b2_ini',
            field=models.DateField(blank=True, null=True, verbose_name='B2 — Início do lançamento'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='notas_b3_fim',
            field=models.DateField(blank=True, null=True, verbose_name='B3 — Fim do lançamento'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='notas_b3_ini',
            field=models.DateField(blank=True, null=True, verbose_name='B3 — Início do lançamento'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='notas_b4_fim',
            field=models.DateField(blank=True, null=True, verbose_name='B4 — Fim do lançamento'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='notas_b4_ini',
            field=models.DateField(blank=True, null=True, verbose_name='B4 — Início do lançamento'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='periodo_notas_fim',
            field=models.DateField(blank=True, help_text='Usado somente se o bimestre não tiver datas próprias configuradas.', null=True, verbose_name='Período global — Fim (fallback)'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='periodo_notas_ini',
            field=models.DateField(blank=True, help_text='Usado somente se o bimestre não tiver datas próprias configuradas.', null=True, verbose_name='Período global — Início (fallback)'),
        ),
    ]
