# Generated by Django 6.0.3 on 2026-06-16 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_notabimestral_nao_avaliado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notabimestral',
            options={'verbose_name': 'Nota Bimestral', 'verbose_name_plural': 'Notas Bimestrais'},
        ),
        migrations.CreateModel(
            name='ProvaAuxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pa', models.IntegerField(choices=[(1, 'PA1'), (2, 'PA2')], verbose_name='Número da PA')),
                ('nota', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Nota da PA')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provas_auxiliares', to='core.aluno')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anoletivo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
                ('lancado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.professor')),
            ],
            options={
                'verbose_name': 'Prova Auxiliar',
                'verbose_name_plural': 'Provas Auxiliares',
                'unique_together': {('aluno', 'disciplina', 'ano_letivo', 'numero_pa')},
            },
        ),
    ]
