# Generated by Django 6.0.3 on 2026-06-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_notabimestral_options_provaauxiliar'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='notas_pa1_fim',
            field=models.DateField(blank=True, null=True, verbose_name='PA1 — Fim do lançamento'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='notas_pa1_ini',
            field=models.DateField(blank=True, null=True, verbose_name='PA1 — Início do lançamento'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='notas_pa2_fim',
            field=models.DateField(blank=True, null=True, verbose_name='PA2 — Fim do lançamento'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='notas_pa2_ini',
            field=models.DateField(blank=True, null=True, verbose_name='PA2 — Início do lançamento'),
        ),
    ]
