# Generated by Django 6.0.3 on 2026-06-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_split_multi_student_ocorrencias'),
        ('core', '0027_configuracao_notas_pa1_fim_and_more'),
    ]

    operations = [
    ]
