# Generated by Django 6.0.3 on 2026-06-30 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_merge_20260617_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notabimestral',
            options={'ordering': ['aluno__nome', 'bimestre'], 'verbose_name': 'Nota Bimestral', 'verbose_name_plural': 'Notas Bimestrais'},
        ),
        migrations.AlterModelOptions(
            name='provaauxiliar',
            options={'ordering': ['aluno__nome'], 'verbose_name': 'Prova Auxiliar', 'verbose_name_plural': 'Provas Auxiliares'},
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.professor', verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
