# Generated by Django 6.0.3 on 2026-06-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_notabimestral_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='avisos_arquivos/', verbose_name='Anexo (PDF)'),
        ),
    ]
