# Generated by Django 6.0.3 on 2026-07-02 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_aviso_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='notas_rec_final_fim',
            field=models.DateField(blank=True, null=True, verbose_name='REC Final — Fim do lançamento'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='notas_rec_final_ini',
            field=models.DateField(blank=True, null=True, verbose_name='REC Final — Início do lançamento'),
        ),
        migrations.CreateModel(
            name='RecuperacaoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Nota da Recuperação Final')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperacoes_finais', to='core.aluno')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anoletivo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
                ('lancado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.professor')),
            ],
            options={
                'verbose_name': 'Recuperação Final',
                'verbose_name_plural': 'Recuperações Finais',
                'ordering': ['aluno__nome'],
                'unique_together': {('aluno', 'disciplina', 'ano_letivo')},
            },
        ),
    ]
