# Generated by Django 6.0.7 on 2026-08-24 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_configuracao_notas_rec_final_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notabimestral',
            name='nao_avaliado',
            field=models.BooleanField(default=False, help_text='Quando verdadeiro, o aluno não realizou a avaliação. A nota final é contabilizada como 0,00.', verbose_name='Não Avaliado (ausente)'),
        ),
        migrations.AlterField(
            model_name='notabimestral',
            name='nota_final',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='Nota Final (calculada)'),
        ),
        migrations.AlterField(
            model_name='notabimestral',
            name='nota_prova',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota da Prova'),
        ),
        migrations.AlterField(
            model_name='notabimestral',
            name='nota_simulado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota do Simulado (interno)'),
        ),
        migrations.AlterField(
            model_name='provaauxiliar',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota da PA'),
        ),
        migrations.AlterField(
            model_name='recuperacaofinal',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota da Recuperação Final'),
        ),
        migrations.CreateModel(
            name='ConselhoClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promovido', models.BooleanField(default=False, verbose_name='Promovido pelo Conselho')),
                ('observacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação / Ata')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisoes_conselho', to='core.aluno')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anoletivo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
                ('lancado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.professor')),
            ],
            options={
                'verbose_name': 'Decisão do Conselho de Classe',
                'verbose_name_plural': 'Decisões do Conselho de Classe',
                'ordering': ['aluno__nome'],
                'unique_together': {('aluno', 'disciplina', 'ano_letivo')},
            },
        ),
    ]
