# Generated by Django 6.0.7 on 2026-08-24 20:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_notabimestral_nao_avaliado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoCoordenacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('ORIENTACAO', 'Orientação ao Aluno'), ('COMUNICADO_FAMILIA', 'Comunicado enviado à Família'), ('REUNIAO_RESPONSAVEIS', 'Reunião com os Responsáveis'), ('ADVERTENCIA', 'Advertência Escrita'), ('SUSPENSAO', 'Suspensão'), ('OUTRO', 'Outra Ação')], default='ORIENTACAO', max_length=50, verbose_name='Tipo de Ação')),
                ('descricao', models.TextField(blank=True, verbose_name='Observações / Detalhes da Ação')),
                ('data_acao', models.DateField(default=datetime.date.today, verbose_name='Data da Ação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_coordenacao', to='core.aluno', verbose_name='Aluno')),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_coordenacao_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('ocorrencias', models.ManyToManyField(blank=True, related_name='acoes_coordenacao', to='core.ocorrencia', verbose_name='Ocorrências Vinculadas')),
            ],
            options={
                'verbose_name': 'Ação da Coordenação',
                'verbose_name_plural': 'Ações da Coordenação',
                'ordering': ['-data_acao', '-criado_em'],
            },
        ),
    ]
