# Generated by Django 6.0.7 on 2026-08-24 22:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_acaocoordenacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontuacaoSubdisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(choices=[('6', '6º Ano EF'), ('7', '7º Ano EF'), ('8', '8º Ano EF'), ('9', '9º Ano EF'), ('1', '1ª Série EM'), ('2', '2ª Série EM'), ('3', '3ª Série EM')], max_length=2, verbose_name='Série / Ano')),
                ('pontuacao_maxima', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Valor máximo da nota para esta subdisciplina nesta série (ex: 4,00).', max_digits=4, verbose_name='Pontuação Máxima')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes_subdisciplinas', to='core.anoletivo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes_serie', to='core.disciplina')),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes_subdisciplinas', to='core.escola')),
            ],
            options={
                'verbose_name': 'Pontuação de Subdisciplina',
                'verbose_name_plural': 'Pontuações de Subdisciplinas',
                'ordering': ['ano_letivo', 'serie', 'disciplina__grupo__ordem_boletim', 'disciplina__nome'],
                'unique_together': {('ano_letivo', 'escola', 'serie', 'disciplina')},
            },
        ),
    ]
