# Generated by Django 6.0.7 on 2026-08-25 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_configurar_eletivas_grupos_pontuacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaEletiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_eletivas', to='core.aluno', verbose_name='Aluno')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_eletivas', to='core.anoletivo', verbose_name='Ano Letivo')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_alunos', to='core.disciplina', verbose_name='Disciplina / Aprofundamento')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_alunos', to='core.grupodisciplina', verbose_name='Grupo Eletivo')),
            ],
            options={
                'verbose_name': 'Matrícula em Eletiva / Aprofundamento',
                'verbose_name_plural': 'Matrículas em Eletivas / Aprofundamentos',
                'ordering': ['aluno__nome'],
            },
        ),
    ]
