# Generated by Django 6.0.7 on 2026-08-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_matriculaeletiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='telefone_responsavel',
            field=models.CharField(blank=True, help_text='Ex: (21) 99999-9999', max_length=30, null=True, verbose_name='Telefone / WhatsApp do Responsável'),
        ),
    ]
